name: Render Bacon Plot to html

on:
  push:
  workflow_dispatch:

jobs:
  render-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies for HTML rendering
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R packages
        run: |
          install.packages(c("rmarkdown", "knitr", "tinytex"), dependencies = TRUE)
          tinytex::install_tinytex()
        shell: Rscript {0}

      - name: Install rbacon (from source in repo or CRAN)
        run: |
          install.packages(".", repos = NULL, type = "source")
        shell: Rscript {0}

      - name: Render testBaconplots.Rmd to PDF
        run: |
          rmarkdown::render("testBaconplots.Rmd", output_format = "html_document")
        shell: Rscript {0}

- name: Debugging: Check available actions
        run: |
          echo "Available actions:"
          ls -alh /actions/

      - name: Upload HTML output
        uses: actions/upload-artifact@v2
        with:
          name: bacon-html
          path: testBaconplots.html
