name: Render Bacon Plot to HTML

on:
  push:
  workflow_dispatch:

jobs:
  render-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2		

      - name: Install system dependencies for HTML rendering
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libpng-dev

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install R packages
        run: |
          install.packages(c("rmarkdown", "knitr", "coda", "rintcal", "rice"), dependencies = TRUE)
        shell: Rscript {0}

      - name: Clean previous builds
        run: |
          rm -rf rbacon/src/*.o rbacon/src/*.so rbacon/src/*.dll rbacon/libs

      - name: Install rbacon (from source in repo or CRAN)
        run: |
          install.packages(".", repos = NULL, type = "source")
        shell: Rscript {0}

      - name: Render testBaconplots.Rmd to HTML
        run: |
          rmarkdown::render("testBaconplots.Rmd", output_format = "html_document")
        shell: Rscript {0}

      - name: Upload HTML output
        uses: actions/upload-artifact@v4
        with:
          name: bacon-html-ubuntu
          path: testBaconplots.html

jobs:
  render-html:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2		

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install R packages
        run: |
          install.packages(c("rmarkdown", "knitr", "coda", "rintcal", "rice"), dependencies = TRUE)
        shell: Rscript {0}

      - name: Clean previous builds
        run: |
          unlink(c("rbacon/src/*.o", "rbacon/src/*.so", "rbacon/src/*.dll", "rbacon/libs"), recursive = TRUE)

      - name: Install rbacon (from source in repo)
        run: |
          install.packages(".", repos = NULL, type = "source")
        shell: Rscript {0}

      - name: Render testBaconplots.Rmd to HTML
        run: |
          rmarkdown::render("testBaconplots.Rmd", output_format = "html_document")
        shell: Rscript {0}

      - name: Upload HTML output
        uses: actions/upload-artifact@v4
        with:
          name: bacon-html-windows
          path: testBaconplots.html
