name: Render Bacon Plot to PDF

on:
  push:

  workflow_dispatch:

jobs:
  render-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies for PDF rendering
        run: |
          sudo apt-get update
          sudo apt-get install -y ghostscript libfribidi-dev libharfbuzz-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev

      - name: Install R packages
        run: |
          install.packages(c("rmarkdown", "knitr", "tinytex"), dependencies = TRUE)
          tinytex::install_tinytex()
        shell: Rscript {0}

      - name: Install rbacon (from source in repo or CRAN)
        run: |
          install.packages(".", repos = NULL, type = "source")
        shell: Rscript {0}

      - name: Render testBaconplots.Rmd to PDF
        run: |
          rmarkdown::render("testBaconplots.Rmd", output_format = "pdf_document")
        shell: Rscript {0}

      - name: Upload PDF output
        uses: actions/upload-artifact@v3
        with:
          name: bacon-pdf
          path: testBaconplots.pdf
